name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    # UTC 时区差8个小时
    - cron : '00 00 * * *'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run:  cd hello & cargo build --verbose
    - name: Run tests
      run: cd hello & cargo test --verbose
